---
PROBLEM_SETNAME: "DUMMY"
SAVE_REWARDS: 0
LIVEVIEW: 1
VERBOSE: 0
DELETE_OLD_DATA: 0
N_EPISODES: 5000
GAMMA: 0.8
EPSILON_START: 1
EPSILON_END: 0.01
EPSILON_DECAY: 0.9975
TAU: 0.005
LR: 0.006
BATCH_SIZE: 128
HIDDEN_LAYER_DIM: 128
REPLAY_BUFFER_SIZE: 10000
UPDATE_FREQ: 1
BIG_M: 1500
BETA: 0.5
...