---
PROBLEM_SETNAME: "DUMMY"
PROBLEM_COUNT: 1
KEEPPHY: 1
PHY:
  MODE: "FROMGML@./data/__internals__/SndLib/pioro40.gml"
  NODECOUNT:
    min: 10
    max: 100
  NODECAP:
    min: 1000
    max: 1000
  LINKCAP:
    min: 1000
    max: 1000
  LINKDISRATE: 0.0
SFCSET:
  MODE: "linear"
  SFCCOUNT: 100
  KEEPSFC: 0
  NODECOUNT:
    min: 5
    max: 5
  NODEREQ:
    min: 2
    max: 2
  LINKREQ:
    min: 2
    max: 2
...