---
PROBLEM_SETNAME: "DUMMY"
SOLVER: "ILP@GUROBI"
TIMELIMIT: 3600
LOGPATH: "./data/logs"
...
# ---
# PROBLEM_SETNAME: "DUMMY"
# SOLVER: "ILP@CBC"
# TIMELIMIT: 180
# LOGPATH: "./data/logs"
# ...
---
PROBLEM_SETNAME: "DUMMY"
SOLVER: "QL@./data/__internals__/QLearn/DUMMY.pkl.gz"
TIMELIMIT: 180
LOGPATH: "./data/logs"
...
---
PROBLEM_SETNAME: "DUMMY"
SOLVER: "DQL@./data/__internals__/DQL/DUMMY.pkl.gz"
TIMELIMIT: 180
LOGPATH: "./data/logs"
...
---
PROBLEM_SETNAME: "DUMMY"
SOLVER: "GREEDY"
TIMELIMIT: 180
LOGPATH: "./data/logs"
...