---
PROBLEM_SETNAME: "DUMMY"
SAVE_REWARDS: 0
LIVEVIEW: 1
VERBOSE: 0
DELETE_OLD_DATA: 1
N_EPISODES: 5000
ALPHA: 0.009
GAMMA: 0.8
EPSILON_START: 1
EPSILON_END: 0.01
EPSILON_DECAY: 0.000198
BIG_M: 1500
BETA: 20
...